Wrap fileDescriptorRatioGauge which breaks in java9
Java9 fails with `InaccessibleObjectException` which causes all metric
reporting to fail. This is a new exception in java9 so we can't catch it
in Java8, simply return 0 if exception is thrown. This is tested in
java8/java9

```
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @385c9627
```